/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Pantallas;


/**
 *
 * @author Luis
 */
public class PanelCronogramaPago extends javax.swing.JPanel {

    /**
     * Creates new form NewJPanel
     */
    public PanelCronogramaPago() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        PnlFondo = new javax.swing.JPanel();
        PnlBase = new javax.swing.JPanel();
        BtnCerrar = new javax.swing.JButton();
        BtnOpc1 = new javax.swing.JButton();
        BtnOpc2 = new javax.swing.JButton();
        BtnOpc3 = new javax.swing.JButton();
        BtnOpc4 = new javax.swing.JButton();
        BtnOpc5 = new javax.swing.JButton();
        BtnOpc6 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        BtnOpc7 = new javax.swing.JButton();
        BtnOpc8 = new javax.swing.JButton();
        BtnOpc91 = new javax.swing.JButton();

        jFrame1.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        jFrame1.setMinimumSize(new java.awt.Dimension(1160, 607));

        PnlFondo.setBackground(new java.awt.Color(0, 153, 255));
        PnlFondo.setMinimumSize(new java.awt.Dimension(1160, 607));

        PnlBase.setBackground(new java.awt.Color(57, 91, 126));
        PnlBase.setPreferredSize(new java.awt.Dimension(1160, 537));

        javax.swing.GroupLayout PnlBaseLayout = new javax.swing.GroupLayout(PnlBase);
        PnlBase.setLayout(PnlBaseLayout);
        PnlBaseLayout.setHorizontalGroup(
            PnlBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        PnlBaseLayout.setVerticalGroup(
            PnlBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 537, Short.MAX_VALUE)
        );

        BtnCerrar.setBackground(new java.awt.Color(255, 0, 0));
        BtnCerrar.setForeground(new java.awt.Color(255, 255, 255));
        BtnCerrar.setBorder(null);
        BtnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCerrarActionPerformed(evt);
            }
        });

        BtnOpc1.setBackground(new java.awt.Color(17, 17, 103));
        BtnOpc1.setFont(new java.awt.Font("Lucida Console", 1, 10)); // NOI18N
        BtnOpc1.setForeground(new java.awt.Color(255, 255, 255));
        BtnOpc1.setText("Opcion 1");
        BtnOpc1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 15, 0, 0, new java.awt.Color(0, 0, 0)));
        BtnOpc1.setBorderPainted(false);
        BtnOpc1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        BtnOpc1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BtnOpc1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        BtnOpc1.setIconTextGap(15);
        BtnOpc1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnOpc1ActionPerformed(evt);
            }
        });

        BtnOpc2.setBackground(new java.awt.Color(17, 17, 103));
        BtnOpc2.setFont(new java.awt.Font("Lucida Console", 1, 10)); // NOI18N
        BtnOpc2.setForeground(new java.awt.Color(255, 255, 255));
        BtnOpc2.setText("Opcion 2");
        BtnOpc2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 15, 0, 0, new java.awt.Color(0, 0, 0)));
        BtnOpc2.setBorderPainted(false);
        BtnOpc2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        BtnOpc2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BtnOpc2.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        BtnOpc2.setIconTextGap(15);
        BtnOpc2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnOpc2ActionPerformed(evt);
            }
        });

        BtnOpc3.setBackground(new java.awt.Color(17, 17, 103));
        BtnOpc3.setFont(new java.awt.Font("Lucida Console", 1, 10)); // NOI18N
        BtnOpc3.setForeground(new java.awt.Color(255, 255, 255));
        BtnOpc3.setText("Opcion 3");
        BtnOpc3.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 15, 0, 0, new java.awt.Color(0, 0, 0)));
        BtnOpc3.setBorderPainted(false);
        BtnOpc3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        BtnOpc3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BtnOpc3.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        BtnOpc3.setIconTextGap(15);
        BtnOpc3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnOpc3ActionPerformed(evt);
            }
        });

        BtnOpc4.setBackground(new java.awt.Color(17, 17, 103));
        BtnOpc4.setFont(new java.awt.Font("Lucida Console", 1, 10)); // NOI18N
        BtnOpc4.setForeground(new java.awt.Color(255, 255, 255));
        BtnOpc4.setText("Opcion 4");
        BtnOpc4.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 15, 0, 0, new java.awt.Color(0, 0, 0)));
        BtnOpc4.setBorderPainted(false);
        BtnOpc4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        BtnOpc4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BtnOpc4.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        BtnOpc4.setIconTextGap(15);
        BtnOpc4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnOpc4ActionPerformed(evt);
            }
        });

        BtnOpc5.setBackground(new java.awt.Color(17, 17, 103));
        BtnOpc5.setFont(new java.awt.Font("Lucida Console", 1, 10)); // NOI18N
        BtnOpc5.setForeground(new java.awt.Color(255, 255, 255));
        BtnOpc5.setText("Opcion 5");
        BtnOpc5.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 15, 0, 0, new java.awt.Color(0, 0, 0)));
        BtnOpc5.setBorderPainted(false);
        BtnOpc5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        BtnOpc5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BtnOpc5.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        BtnOpc5.setIconTextGap(15);
        BtnOpc5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnOpc5ActionPerformed(evt);
            }
        });

        BtnOpc6.setBackground(new java.awt.Color(17, 17, 103));
        BtnOpc6.setFont(new java.awt.Font("Lucida Console", 1, 10)); // NOI18N
        BtnOpc6.setForeground(new java.awt.Color(255, 255, 255));
        BtnOpc6.setText("Opcion 1");
        BtnOpc6.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 15, 0, 0, new java.awt.Color(0, 0, 0)));
        BtnOpc6.setBorderPainted(false);
        BtnOpc6.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        BtnOpc6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BtnOpc6.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        BtnOpc6.setIconTextGap(15);
        BtnOpc6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnOpc6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PnlFondoLayout = new javax.swing.GroupLayout(PnlFondo);
        PnlFondo.setLayout(PnlFondoLayout);
        PnlFondoLayout.setHorizontalGroup(
            PnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlFondoLayout.createSequentialGroup()
                .addComponent(BtnOpc1, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(BtnOpc2, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(BtnOpc3, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(BtnOpc4, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(BtnOpc5, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(BtnOpc6, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(BtnCerrar, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE))
            .addComponent(PnlBase, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        PnlFondoLayout.setVerticalGroup(
            PnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlFondoLayout.createSequentialGroup()
                .addGroup(PnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BtnOpc1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnOpc2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnOpc3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnOpc4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnOpc5, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnOpc6, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addComponent(PnlBase, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PnlFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PnlFondo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.setBackground(new java.awt.Color(255, 102, 102));

        jPanel2.setBackground(new java.awt.Color(153, 102, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 2, 18)); // NOI18N
        jLabel1.setText("CRONOGRAMA DE PAGOS");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "MES", "VENCIMIENTO", "AMORTIZACION", "INTERES", "CUOTA", "SALDO"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        BtnOpc7.setBackground(new java.awt.Color(0, 51, 204));
        BtnOpc7.setFont(new java.awt.Font("Verdana", 3, 14)); // NOI18N
        BtnOpc7.setForeground(new java.awt.Color(255, 255, 255));
        BtnOpc7.setText("Exportar a EXCEL");
        BtnOpc7.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 15, 0, 0, new java.awt.Color(0, 0, 0)));
        BtnOpc7.setBorderPainted(false);
        BtnOpc7.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        BtnOpc7.setHideActionText(true);
        BtnOpc7.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        BtnOpc7.setIconTextGap(15);
        BtnOpc7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnOpc7ActionPerformed(evt);
            }
        });

        BtnOpc8.setBackground(new java.awt.Color(0, 51, 204));
        BtnOpc8.setFont(new java.awt.Font("Verdana", 3, 14)); // NOI18N
        BtnOpc8.setForeground(new java.awt.Color(255, 255, 255));
        BtnOpc8.setText("Ingresar Datos nuevos");
        BtnOpc8.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 15, 0, 0, new java.awt.Color(0, 0, 0)));
        BtnOpc8.setBorderPainted(false);
        BtnOpc8.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        BtnOpc8.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        BtnOpc8.setIconTextGap(15);
        BtnOpc8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnOpc8ActionPerformed(evt);
            }
        });

        BtnOpc91.setBackground(new java.awt.Color(0, 51, 204));
        BtnOpc91.setFont(new java.awt.Font("Verdana", 3, 14)); // NOI18N
        BtnOpc91.setForeground(new java.awt.Color(255, 255, 255));
        BtnOpc91.setText("Ir a oferta inicial");
        BtnOpc91.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 15, 0, 0, new java.awt.Color(0, 0, 0)));
        BtnOpc91.setBorderPainted(false);
        BtnOpc91.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        BtnOpc91.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        BtnOpc91.setIconTextGap(15);
        BtnOpc91.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnOpc91ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(BtnOpc91, javax.swing.GroupLayout.DEFAULT_SIZE, 284, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(BtnOpc8, javax.swing.GroupLayout.DEFAULT_SIZE, 284, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(BtnOpc7, javax.swing.GroupLayout.DEFAULT_SIZE, 284, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BtnOpc91, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(BtnOpc8, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(BtnOpc7, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 814, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BtnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCerrarActionPerformed

    }//GEN-LAST:event_BtnCerrarActionPerformed

    private void BtnOpc1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnOpc1ActionPerformed

    }//GEN-LAST:event_BtnOpc1ActionPerformed

    private void BtnOpc2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnOpc2ActionPerformed

    }//GEN-LAST:event_BtnOpc2ActionPerformed

    private void BtnOpc3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnOpc3ActionPerformed

    }//GEN-LAST:event_BtnOpc3ActionPerformed

    private void BtnOpc4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnOpc4ActionPerformed

    }//GEN-LAST:event_BtnOpc4ActionPerformed

    private void BtnOpc5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnOpc5ActionPerformed

    }//GEN-LAST:event_BtnOpc5ActionPerformed

    private void BtnOpc6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnOpc6ActionPerformed

    }//GEN-LAST:event_BtnOpc6ActionPerformed

    private void BtnOpc7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnOpc7ActionPerformed
 
    }//GEN-LAST:event_BtnOpc7ActionPerformed

    private void BtnOpc8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnOpc8ActionPerformed

    }//GEN-LAST:event_BtnOpc8ActionPerformed

    private void BtnOpc91ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnOpc91ActionPerformed
 
    }//GEN-LAST:event_BtnOpc91ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCerrar;
    private javax.swing.JButton BtnOpc1;
    private javax.swing.JButton BtnOpc2;
    private javax.swing.JButton BtnOpc3;
    private javax.swing.JButton BtnOpc4;
    private javax.swing.JButton BtnOpc5;
    private javax.swing.JButton BtnOpc6;
    private javax.swing.JButton BtnOpc7;
    private javax.swing.JButton BtnOpc8;
    private javax.swing.JButton BtnOpc91;
    private javax.swing.JPanel PnlBase;
    private javax.swing.JPanel PnlFondo;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
